### ISSUE TITLE
Unexpected behavior- Copy Layers To Bitmap

### ISSUE THREAD

**Issue by jijoam** [SpringRoll/FlashToolkit#1]
I am using version 1.1.2 of the toolkit and I have observed a few issues/challanges while using the command - Copy Layers To Bitmap.

> 1. Multiple frames in the timeline are converted to a single bitmap.
> 2. In some cases it throws an error and doesn't convert the frames to bitmap.
> 3. If there is a label layer above the vector layer/s, it doesn't convert to a bitmap but creates a copy of the layers

![error](https://cloud.githubusercontent.com/assets/14106955/9656284/cd50741c-5254-11e5-96f6-3feea6f2c0ad.PNG)

**Comment by bigtimebuddy** [comment]
@jijoam Would it be possible upload an FLA with just that symbol so we can test what's happening?

**Comment by jijoam** [comment]
@bigtimebuddy The FLA can be downloaded from the below link. 

path> http://cst-ts.excelindia.com/SharedTo/
file> hand.zip

**Comment by bigtimebuddy** [comment]
Verified.

**Comment by bigtimebuddy** [comment]
It seems that the Copy Layers To Bitmap only works with 1 or 2 layers but breaks on 3, try copying the "Layer 2" contents to "comp" layer and deleting "Layer 2".

**Comment by bigtimebuddy** [comment]
Fixed in 1.1.3 release. Was able to test and successful convert.

**Comment by jijoam** [comment]
@bigtimebuddy Thank you, it works correctly now. 

Just to add as an info, I noticed that if any/all of the layers are locked and the command is used then it doesn't convert to a bitmap but creates a copy of the layers.

**Comment by bigtimebuddy** [comment]
Good to know. We'll address this in the next release.
