### ISSUE TITLE
Scaling Copy Layers To Bitmap and maintaining original line weight

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/FlashToolkit#6]
When I create a bitmap at 2x the original size, the line weight comes in half as thick. Is there a setting or method to maintain the line thickness? This may speak more to my inexperience with Animate than this specific tool, but any pointers would be appreciated!

![image](https://cloud.githubusercontent.com/assets/1324745/21287199/0ec5c3e6-c434-11e6-9baa-31e680378e6f.png)

**Comment by bigtimebuddy** [comment]
You need to convert lines to fills if you want to maintain the original weight or else it renders the bitmap at 100%, not at the size it's scaled on the stage.

**Comment by probityrules** [comment]
Awesome; thanks for the help! I'll try it out.
